// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: labelList.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "labelList.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tutorial {

namespace {

const ::google::protobuf::Descriptor* LabelList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LabelList_reflection_ = NULL;
const ::google::protobuf::Descriptor* LabelList_Label_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LabelList_Label_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_labelList_2eproto() {
  protobuf_AddDesc_labelList_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "labelList.proto");
  GOOGLE_CHECK(file != NULL);
  LabelList_descriptor_ = file->message_type(0);
  static const int LabelList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList, label_),
  };
  LabelList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LabelList_descriptor_,
      LabelList::default_instance_,
      LabelList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LabelList));
  LabelList_Label_descriptor_ = LabelList_descriptor_->nested_type(0);
  static const int LabelList_Label_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, firstkey_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, label_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, face_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, sendtime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, praisecount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, sid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, seq_),
  };
  LabelList_Label_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LabelList_Label_descriptor_,
      LabelList_Label::default_instance_,
      LabelList_Label_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LabelList_Label, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LabelList_Label));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_labelList_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LabelList_descriptor_, &LabelList::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LabelList_Label_descriptor_, &LabelList_Label::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_labelList_2eproto() {
  delete LabelList::default_instance_;
  delete LabelList_reflection_;
  delete LabelList_Label::default_instance_;
  delete LabelList_Label_reflection_;
}

void protobuf_AddDesc_labelList_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017labelList.proto\022\010tutorial\"\256\001\n\tLabelLis"
    "t\022(\n\005label\030\001 \003(\0132\031.tutorial.LabelList.La"
    "bel\032w\n\005Label\022\020\n\010firstKey\030\001 \002(\t\022\r\n\005label\030"
    "\002 \001(\t\022\014\n\004face\030\003 \001(\t\022\020\n\010sendTime\030\004 \002(\003\022\023\n"
    "\013praiseCount\030\005 \002(\005\022\013\n\003sid\030\006 \002(\005\022\013\n\003seq\030\007"
    " \002(\tB\036\n\013com.ii.pbpoB\017LabelListReturn", 236);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "labelList.proto", &protobuf_RegisterTypes);
  LabelList::default_instance_ = new LabelList();
  LabelList_Label::default_instance_ = new LabelList_Label();
  LabelList::default_instance_->InitAsDefaultInstance();
  LabelList_Label::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_labelList_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_labelList_2eproto {
  StaticDescriptorInitializer_labelList_2eproto() {
    protobuf_AddDesc_labelList_2eproto();
  }
} static_descriptor_initializer_labelList_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int LabelList_Label::kFirstKeyFieldNumber;
const int LabelList_Label::kLabelFieldNumber;
const int LabelList_Label::kFaceFieldNumber;
const int LabelList_Label::kSendTimeFieldNumber;
const int LabelList_Label::kPraiseCountFieldNumber;
const int LabelList_Label::kSidFieldNumber;
const int LabelList_Label::kSeqFieldNumber;
#endif  // !_MSC_VER

LabelList_Label::LabelList_Label()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LabelList_Label::InitAsDefaultInstance() {
}

LabelList_Label::LabelList_Label(const LabelList_Label& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LabelList_Label::SharedCtor() {
  _cached_size_ = 0;
  firstkey_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  label_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  face_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  sendtime_ = GOOGLE_LONGLONG(0);
  praisecount_ = 0;
  sid_ = 0;
  seq_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LabelList_Label::~LabelList_Label() {
  SharedDtor();
}

void LabelList_Label::SharedDtor() {
  if (firstkey_ != &::google::protobuf::internal::kEmptyString) {
    delete firstkey_;
  }
  if (label_ != &::google::protobuf::internal::kEmptyString) {
    delete label_;
  }
  if (face_ != &::google::protobuf::internal::kEmptyString) {
    delete face_;
  }
  if (seq_ != &::google::protobuf::internal::kEmptyString) {
    delete seq_;
  }
  if (this != default_instance_) {
  }
}

void LabelList_Label::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LabelList_Label::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LabelList_Label_descriptor_;
}

const LabelList_Label& LabelList_Label::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_labelList_2eproto();
  return *default_instance_;
}

LabelList_Label* LabelList_Label::default_instance_ = NULL;

LabelList_Label* LabelList_Label::New() const {
  return new LabelList_Label;
}

void LabelList_Label::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_firstkey()) {
      if (firstkey_ != &::google::protobuf::internal::kEmptyString) {
        firstkey_->clear();
      }
    }
    if (has_label()) {
      if (label_ != &::google::protobuf::internal::kEmptyString) {
        label_->clear();
      }
    }
    if (has_face()) {
      if (face_ != &::google::protobuf::internal::kEmptyString) {
        face_->clear();
      }
    }
    sendtime_ = GOOGLE_LONGLONG(0);
    praisecount_ = 0;
    sid_ = 0;
    if (has_seq()) {
      if (seq_ != &::google::protobuf::internal::kEmptyString) {
        seq_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LabelList_Label::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string firstKey = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_firstkey()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->firstkey().data(), this->firstkey().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_label;
        break;
      }

      // optional string label = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_label:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_label()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->label().data(), this->label().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_face;
        break;
      }

      // optional string face = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_face:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_face()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->face().data(), this->face().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_sendTime;
        break;
      }

      // required int64 sendTime = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_sendTime:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sendtime_)));
          set_has_sendtime();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_praiseCount;
        break;
      }

      // required int32 praiseCount = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_praiseCount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &praisecount_)));
          set_has_praisecount();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_sid;
        break;
      }

      // required int32 sid = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_sid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sid_)));
          set_has_sid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_seq;
        break;
      }

      // required string seq = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_seq:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_seq()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->seq().data(), this->seq().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void LabelList_Label::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string firstKey = 1;
  if (has_firstkey()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->firstkey().data(), this->firstkey().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->firstkey(), output);
  }

  // optional string label = 2;
  if (has_label()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->label().data(), this->label().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->label(), output);
  }

  // optional string face = 3;
  if (has_face()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->face().data(), this->face().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->face(), output);
  }

  // required int64 sendTime = 4;
  if (has_sendtime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->sendtime(), output);
  }

  // required int32 praiseCount = 5;
  if (has_praisecount()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->praisecount(), output);
  }

  // required int32 sid = 6;
  if (has_sid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->sid(), output);
  }

  // required string seq = 7;
  if (has_seq()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->seq().data(), this->seq().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      7, this->seq(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* LabelList_Label::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string firstKey = 1;
  if (has_firstkey()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->firstkey().data(), this->firstkey().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->firstkey(), target);
  }

  // optional string label = 2;
  if (has_label()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->label().data(), this->label().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->label(), target);
  }

  // optional string face = 3;
  if (has_face()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->face().data(), this->face().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->face(), target);
  }

  // required int64 sendTime = 4;
  if (has_sendtime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->sendtime(), target);
  }

  // required int32 praiseCount = 5;
  if (has_praisecount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->praisecount(), target);
  }

  // required int32 sid = 6;
  if (has_sid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->sid(), target);
  }

  // required string seq = 7;
  if (has_seq()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->seq().data(), this->seq().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->seq(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int LabelList_Label::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string firstKey = 1;
    if (has_firstkey()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->firstkey());
    }

    // optional string label = 2;
    if (has_label()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->label());
    }

    // optional string face = 3;
    if (has_face()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->face());
    }

    // required int64 sendTime = 4;
    if (has_sendtime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->sendtime());
    }

    // required int32 praiseCount = 5;
    if (has_praisecount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->praisecount());
    }

    // required int32 sid = 6;
    if (has_sid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->sid());
    }

    // required string seq = 7;
    if (has_seq()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->seq());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LabelList_Label::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LabelList_Label* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LabelList_Label*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LabelList_Label::MergeFrom(const LabelList_Label& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_firstkey()) {
      set_firstkey(from.firstkey());
    }
    if (from.has_label()) {
      set_label(from.label());
    }
    if (from.has_face()) {
      set_face(from.face());
    }
    if (from.has_sendtime()) {
      set_sendtime(from.sendtime());
    }
    if (from.has_praisecount()) {
      set_praisecount(from.praisecount());
    }
    if (from.has_sid()) {
      set_sid(from.sid());
    }
    if (from.has_seq()) {
      set_seq(from.seq());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LabelList_Label::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LabelList_Label::CopyFrom(const LabelList_Label& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LabelList_Label::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000079) != 0x00000079) return false;

  return true;
}

void LabelList_Label::Swap(LabelList_Label* other) {
  if (other != this) {
    std::swap(firstkey_, other->firstkey_);
    std::swap(label_, other->label_);
    std::swap(face_, other->face_);
    std::swap(sendtime_, other->sendtime_);
    std::swap(praisecount_, other->praisecount_);
    std::swap(sid_, other->sid_);
    std::swap(seq_, other->seq_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LabelList_Label::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LabelList_Label_descriptor_;
  metadata.reflection = LabelList_Label_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int LabelList::kLabelFieldNumber;
#endif  // !_MSC_VER

LabelList::LabelList()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LabelList::InitAsDefaultInstance() {
}

LabelList::LabelList(const LabelList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LabelList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LabelList::~LabelList() {
  SharedDtor();
}

void LabelList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void LabelList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LabelList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LabelList_descriptor_;
}

const LabelList& LabelList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_labelList_2eproto();
  return *default_instance_;
}

LabelList* LabelList::default_instance_ = NULL;

LabelList* LabelList::New() const {
  return new LabelList;
}

void LabelList::Clear() {
  label_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LabelList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tutorial.LabelList.Label label = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_label:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_label()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_label;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void LabelList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .tutorial.LabelList.Label label = 1;
  for (int i = 0; i < this->label_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->label(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* LabelList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .tutorial.LabelList.Label label = 1;
  for (int i = 0; i < this->label_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->label(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int LabelList::ByteSize() const {
  int total_size = 0;

  // repeated .tutorial.LabelList.Label label = 1;
  total_size += 1 * this->label_size();
  for (int i = 0; i < this->label_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->label(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LabelList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LabelList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LabelList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LabelList::MergeFrom(const LabelList& from) {
  GOOGLE_CHECK_NE(&from, this);
  label_.MergeFrom(from.label_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LabelList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LabelList::CopyFrom(const LabelList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LabelList::IsInitialized() const {

  for (int i = 0; i < label_size(); i++) {
    if (!this->label(i).IsInitialized()) return false;
  }
  return true;
}

void LabelList::Swap(LabelList* other) {
  if (other != this) {
    label_.Swap(&other->label_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LabelList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LabelList_descriptor_;
  metadata.reflection = LabelList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tutorial

// @@protoc_insertion_point(global_scope)
